name: logistics_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  gap: ^3.0.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.2
  country_picker: ^2.0.26
  flutter_multi_formatter: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/